# Server Configuration
server:
  port: 8080
  error:
    include-stacktrace: always
  compression:
    enabled: true
  address: 0.0.0.0

# Spring Configuration
spring:
  sql:
    init:
      mode: always
  application:
    name: StudentResultApplication
  jackson:
    date-format: yyyy-MM-dd
    time-zone: IST


  # Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/SpringBootDemo
    username: root
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    defer-datasource-initialization: true
    # Properties
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: create
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: false

# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"


ftpFileUploadPath: /var/www/html/IEIMS/eiin-service
